from app.schemas.base import ApiResponse, HealthResponse
from app.schemas.avatar import (
    AvatarGenerationRequest,
    AvatarGenerationResponse,
    MeasurementsInput,
    SMPLParameters,
    AvatarMesh,
    GenderEnum,
)
from app.schemas.morphotype import (
    MorphotypeCode,
    MorphotypeDefinition,
    MorphotypeListResponse,
    MorphotypeAvatarRequest,
)
from app.schemas.personalization import (
    SkinToneEnum,
    HairColorEnum,
    VisualFeatures,
    PhotoAnalysisResponse,
)
from app.schemas.clothing import (
    ClothingCategory, FabricType, ViewAngle,
    ColorInfo, ContourInfo, PhotoAnalysis,
    DigitizedClothing, DigitizationRequest,
)
from app.schemas.simulation import (
    AnimationType, FabricProperties,
    AvatarSimData, ClothingSimData,
    SimulationRequest, TensionZone,
    FitAnalysis, SimulationFrame, SimulationResponse,
)
from app.schemas.visualization import (
    ClothingMetadata,
    ClothingFrameData,
    UnitySceneConfig,
    StreamStatus,
)
from app.schemas.fit_analysis import (
    FitCategory, TensionLevel, AnatomicZone,
    ZoneAnalysis, SizeComparison,
    DetailedFitAnalysis, FitHistoryEntry, FitTrend,
)
__all__ = [
    "ApiResponse",
    "HealthResponse",
    "AvatarGenerationRequest",
    "AvatarGenerationResponse",
    "MeasurementsInput",
    "SMPLParameters",
    "AvatarMesh",
    "GenderEnum",
    "MorphotypeCode",
    "MorphotypeDefinition",
    "MorphotypeListResponse",
    "MorphotypeAvatarRequest",
    "SkinToneEnum",
    "HairColorEnum",
    "VisualFeatures",
    "PhotoAnalysisResponse",
    "ClothingCategory",
    "FabricType",
    "ViewAngle",
    "ColorInfo",
    "ContourInfo",
    "PhotoAnalysis",
    "DigitizedClothing",
    "DigitizationRequest",
    "AnimationType",
    "FabricProperties",
    "AvatarSimData",
    "ClothingSimData",
    "SimulationRequest",
    "TensionZone",
    "FitAnalysis",
    "SimulationFrame",
    "SimulationResponse",
    "ClothingMetadata", 
    "ClothingFrameData",
    "UnitySceneConfig", 
    "StreamStatus",
    "FitCategory", 
    "TensionLevel", 
    "AnatomicZone",
    "ZoneAnalysis", 
    "SizeComparison",
    "DetailedFitAnalysis", 
    "FitHistoryEntry", 
    "FitTrend",
]