# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.proto import avatar_pb2 as avatar__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in avatar_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class AvatarServiceStub(object):
    """Service principal de gestion des avatars

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateAvatar = channel.unary_unary(
                '/virtufit.avatar.AvatarService/GenerateAvatar',
                request_serializer=avatar__pb2.AvatarGenerationRequest.SerializeToString,
                response_deserializer=avatar__pb2.AvatarGenerationResponse.FromString,
                _registered_method=True)
        self.GetAvatar = channel.unary_unary(
                '/virtufit.avatar.AvatarService/GetAvatar',
                request_serializer=avatar__pb2.GetAvatarRequest.SerializeToString,
                response_deserializer=avatar__pb2.AvatarData.FromString,
                _registered_method=True)
        self.StreamAvatarUpdates = channel.unary_stream(
                '/virtufit.avatar.AvatarService/StreamAvatarUpdates',
                request_serializer=avatar__pb2.GetAvatarRequest.SerializeToString,
                response_deserializer=avatar__pb2.AvatarUpdate.FromString,
                _registered_method=True)


class AvatarServiceServicer(object):
    """Service principal de gestion des avatars

    """

    def GenerateAvatar(self, request, context):
        """Génère un avatar depuis les mensurations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvatar(self, request, context):
        """Récupère un avatar existant
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAvatarUpdates(self, request, context):
        """Stream les mises à jour d'avatar en temps réel
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AvatarServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateAvatar': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateAvatar,
                    request_deserializer=avatar__pb2.AvatarGenerationRequest.FromString,
                    response_serializer=avatar__pb2.AvatarGenerationResponse.SerializeToString,
            ),
            'GetAvatar': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvatar,
                    request_deserializer=avatar__pb2.GetAvatarRequest.FromString,
                    response_serializer=avatar__pb2.AvatarData.SerializeToString,
            ),
            'StreamAvatarUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAvatarUpdates,
                    request_deserializer=avatar__pb2.GetAvatarRequest.FromString,
                    response_serializer=avatar__pb2.AvatarUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'virtufit.avatar.AvatarService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('virtufit.avatar.AvatarService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AvatarService(object):
    """Service principal de gestion des avatars

    """

    @staticmethod
    def GenerateAvatar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/virtufit.avatar.AvatarService/GenerateAvatar',
            avatar__pb2.AvatarGenerationRequest.SerializeToString,
            avatar__pb2.AvatarGenerationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvatar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/virtufit.avatar.AvatarService/GetAvatar',
            avatar__pb2.GetAvatarRequest.SerializeToString,
            avatar__pb2.AvatarData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAvatarUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/virtufit.avatar.AvatarService/StreamAvatarUpdates',
            avatar__pb2.GetAvatarRequest.SerializeToString,
            avatar__pb2.AvatarUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
