# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.proto import simulation_pb2 as simulation__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in simulation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class SimulationServiceStub(object):
    """Service de simulation physique textile

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartSimulation = channel.unary_unary(
                '/virtufit.simulation.SimulationService/StartSimulation',
                request_serializer=simulation__pb2.SimulationRequest.SerializeToString,
                response_deserializer=simulation__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.StreamSimulation = channel.unary_stream(
                '/virtufit.simulation.SimulationService/StreamSimulation',
                request_serializer=simulation__pb2.SimulationRequest.SerializeToString,
                response_deserializer=simulation__pb2.SimulationFrame.FromString,
                _registered_method=True)
        self.GetFitAnalysis = channel.unary_unary(
                '/virtufit.simulation.SimulationService/GetFitAnalysis',
                request_serializer=simulation__pb2.FitAnalysisRequest.SerializeToString,
                response_deserializer=simulation__pb2.FitAnalysisResponse.FromString,
                _registered_method=True)


class SimulationServiceServicer(object):
    """Service de simulation physique textile

    """

    def StartSimulation(self, request, context):
        """Lance une simulation d'essayage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSimulation(self, request, context):
        """Stream les frames de simulation en temps réel
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFitAnalysis(self, request, context):
        """Récupère le rapport d'ajustement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSimulation,
                    request_deserializer=simulation__pb2.SimulationRequest.FromString,
                    response_serializer=simulation__pb2.SimulationResponse.SerializeToString,
            ),
            'StreamSimulation': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSimulation,
                    request_deserializer=simulation__pb2.SimulationRequest.FromString,
                    response_serializer=simulation__pb2.SimulationFrame.SerializeToString,
            ),
            'GetFitAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFitAnalysis,
                    request_deserializer=simulation__pb2.FitAnalysisRequest.FromString,
                    response_serializer=simulation__pb2.FitAnalysisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'virtufit.simulation.SimulationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('virtufit.simulation.SimulationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimulationService(object):
    """Service de simulation physique textile

    """

    @staticmethod
    def StartSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/virtufit.simulation.SimulationService/StartSimulation',
            simulation__pb2.SimulationRequest.SerializeToString,
            simulation__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/virtufit.simulation.SimulationService/StreamSimulation',
            simulation__pb2.SimulationRequest.SerializeToString,
            simulation__pb2.SimulationFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFitAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/virtufit.simulation.SimulationService/GetFitAnalysis',
            simulation__pb2.FitAnalysisRequest.SerializeToString,
            simulation__pb2.FitAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
